# ENTRYPOINT instruction is also like CMD instruction which is used to start the container
#CMD can be over ridden but ENTRYPOINT can't be overridden
# CMD can be used to supply argumnets to the ENTRYPOINT, if required we can over ride CMD at runntime

FROM almalinux:9
CMD ["google.com"]
ENTRYPOINT ["ping"]