# WORkDIR instruction is used to keep that path as our workdir always even if we r in different path.
FROM nginx
WORKDIR /opt/server

RUN useradd roboshop
USER roboshop
CMD ["1000"]
ENTRYPOINT ["sleep"]