# ENV  instruction is used to declare environment variables, we can access these variables inside container
# and container can use these varibles 
FROM nginx
ENV course = "docker" \
    trainer = "siva"
